name: gallery
description: Gallery project to showcase tfytfm_ui
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  tfytfm_ui:
    path: ^0.1.0
  flutter:
    sdk: flutter
  flutter_asset_generator: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
